services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfiles/ops_app/Dockerfile
    container_name: dev
    volumes:
      - ./hse_mlops_hw:/src/hse_mlops_hw/
      - ./data:/src/data
      - ./configs:/src/configs
      - ./.dvc:/src/.dvc
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
