model:
  name: facebook/detr-resnet-50
  dropout: 0.5
  freeze_backbone: false

data:
  train_folder: ../data/train
  test_folder: ../data/test
  val_size: 0.2
  dataloader_num_workers: 4
  batch_size: 32


labels:
  - cat
  - dog

train:
  learning_rate: 2e-5
  weight_decay: 0.01
  num_warmup_steps: 1
  num_training_steps: 1
  grad_accum_steps: 2
  accelerator: auto
  devices: auto
  precision: bf16-mixed
  val_check_interval: 1.0
  overfit_batches: 0
  num_sanity_val_steps: 1
  full_deterministic_mode: false
  benchmark: false
  gradient_clip_val: 1.0
  profiler:
  log_every_n_steps: 1
  batch_size_finder: false
  detect_anomaly: false

artifacts:
  experiment_name: example-experiment
  tracking_uri: postgresql://test:test@localhost:5432/mlflow
  checkpoint:
    use: False
    dirpath: ../data
    filename: "{epoch:02d}-{val_loss:.4f}"
    monitor: val_loss
    save_top_k: 3
    every_n_train_steps:
    every_n_epochs: 1

callbacks:
  model_summary:
    max_depth: 1
