defaults:
  - model: base_model.yaml
  - data: base_data.yaml
  - train: base_train.yaml
  - artifacts: base_artifacts.yaml
  - inference: base_inference.yaml
  - _self_

callbacks:
  model_summary:
    max_depth: 1
