experiment_name: example-experiment
tracking_uri: http://localhost:5000
checkpoint:
  use: True
  dirpath: checkpoints
  filename: "{epoch:02d}-{val_loss:.4f}"
  monitor: val_loss
  save_top_k: 3
  every_n_train:
  every_n_epochs: 1
