experiment_name: example-experiment
tracking_uri: postgresql://test:test@postgres:5432/mlflow
checkpoint:
  use: False
  dirpath: data
  filename: "{epoch:02d}-{val_loss:.4f}"
  monitor: val_loss
  save_top_k: 3
  every_n_train_steps:
  every_n_epochs: 1
