max_epochs: 10
learning_rate: 2e-5
weight_decay: 0.01
num_warmup_steps: 1
num_training_steps: 100
grad_accum_steps: 2
accelerator: auto
devices: auto
precision: 32
val_check_interval: 1.0
overfit_batches: 0
num_sanity_val_steps: 1
full_deterministic_mode: false
benchmark: false
gradient_clip_val: 1.0
profiler: null
log_every_n_steps: 1
batch_size_finder: false
detect_anomaly: false
limit_train_batches: 0.2
